name: Deployment pipeline

on:
  push:
    branches:
      - master

jobs:
  check_code:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        part: [frontend, backend] # runs both in frontend and backend directories
    steps:
      - uses: actions/checkout@v4 # get the code
      - uses: actions/setup-node@v4 # set up node
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
        working-directory: ${{ matrix.part }} # go to both directories
      - name: Check style
        run: npm run eslint
        working-directory: ${{ matrix.part }}
